
import { FaGoogle } from "react-icons/fa"
import styles from './styles.module.css'

import Head from "next/head"
import { signIn } from "next-auth/react"

export default function Login() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Login - Corrige-Me</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.form}>
                <div className={styles.loginTexts}>
                    <h1 className={styles.loginTitle}>Corrige-Me</h1>
                    <h2 className={styles.loginSubtitle}>Entre para corrigir suas redações com IA</h2>
                </div>

                <button onClick={() => signIn('google')} className={styles.loginButton}><FaGoogle size={24} />Entrar com Google</button>
                <div className={styles.loginFooter}>
                    <p className={styles.loginParag}>Login seguro com autenticação Google</p>
                </div>
            </div>
        </div>
    )
}