import Head from "next/head";

import styles from "./styles.module.css";
import { CircularProgressbar, buildStyles } from 'react-circular-progressbar';
import 'react-circular-progressbar/dist/styles.css';
import { FaArrowLeft, FaArrowRight } from "react-icons/fa";
import { useEffect, useState } from "react";

import { GetServerSideProps } from "next";
import { getSession, useSession } from "next-auth/react";


export default function Redacao() {
    const [comp, setComp] = useState(1);
    const [compNota, setCompNota] = useState([120, 200, 200, 160, 120])
    const [color, setColor] = useState('#34498B')

    useEffect(() => {
        if (comp <= 1) {
            setComp(1);
        } else if (comp >= 5) {
            setComp(5);
        }

        switch (comp) {
            case 1:
                setColor('#34498B');
                break;
            case 2:
                setColor('#346b8b');
                break;
            case 3:
                setColor('#34498B');
                break;
            case 4:
                setColor('#346b8b');
                break;
            case 5:
                setColor('#34498B');
                break;
        }
    }, [comp])

    return (
        <div className={styles.container}>

            <Head>
                <title>Redação - Corrige-Me</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.info}>
                <h1 className={styles.title}>Tema da redação</h1>
                <div className={styles.info}>
                    <div className={styles.cardProgress}>
                        <h2 className={styles.cardTitle}>Nota Final</h2>
                        <CircularProgressbar className={styles.progressBar} styles={buildStyles({
                            rotation: 0.75,
                            textColor: '#34498B',
                            pathColor: '#34498B',
                            textSize: '18px',
                            strokeLinecap: "butt"
                        })} value={880} maxValue={1000} text="880" circleRatio={0.5} />
                    </div>
                    <div className={styles.cardProgress}>
                        <h2 className={styles.cardTitle}>Competência {comp}</h2>
                        <div className={styles.cardContent}>
                            <button onClick={() => setComp(comp - 1)} className={styles.sliderButton}> <FaArrowLeft size={24} /> </button>
                            <CircularProgressbar className={styles.progressBarComp} styles={buildStyles({
                                rotation: 0.75,
                                textColor: color,
                                pathColor: color,
                                textSize: '18px',
                                strokeLinecap: "butt"
                            })} value={compNota[comp - 1]} maxValue={200} text={compNota[comp - 1] as unknown as string} circleRatio={0.5} />
                            <button onClick={() => setComp(comp + 1)} className={styles.sliderButton}> <FaArrowRight size={24} /> </button>
                        </div>

                    </div>
                </div>
            </div>
            <div className={styles.actions}>
                <button onClick={() => { location.href = '/historico' }} className={styles.button}>
                    <span className={styles.buttonTop}>Ver minhas redações</span>
                    <span className={styles.buttonBottom}>Veja o seu historico</span>
                </button>
                <button onClick={() => { location.href = '/corrigir' }} className={styles.buttonSecondary}>
                    <span className={styles.buttonTop}>Escrever nova redação</span>
                    <span className={styles.buttonBottom}>Pratique para o ENEM com temas reais</span>
                </button>
            </div>
        </div>
    );
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
    const session = await getSession({ req });

    if (!session?.user) {
        return {
            redirect: {
                destination: '/login',
                permanent: false,
            }
        }
    }


    return {
        props: {
            user: {
                email: session?.user?.email,
            }
        },
    };
};