import Head from "next/head";

import styles from "./styles.module.css";
import { CircularProgressbar, buildStyles } from 'react-circular-progressbar';
import 'react-circular-progressbar/dist/styles.css';
import { FaArrowLeft, FaArrowRight } from "react-icons/fa";
import { useEffect, useState } from "react";

import { GetServerSideProps } from "next";
import { getSession, useSession } from "next-auth/react";

export default function Redacao() {
    const [comp, setComp] = useState(1);
    const [compNota, setCompNota] = useState([120, 200, 200, 160, 120])
    const [color, setColor] = useState('#34498B')

    useEffect(() => {
        if (comp <= 1) {
            setComp(1);
        } else if (comp >= 5) {
            setComp(5);
        }

        switch (comp) {
            case 1:
                setColor('#34498B');
                break;
            case 2:
                setColor('#346b8b');
                break;
            case 3:
                setColor('#34498B');
                break;
            case 4:
                setColor('#346b8b');
                break;
            case 5:
                setColor('#34498B');
                break;
        }
    }, [comp])

    return (
        <div className={styles.container}>

            <Head>
                <title>Historico - Corrige-Me</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.info}>
                <h1 className={styles.title}>Minhas Redações</h1>
                <button onClick={() => location.href = '/historico/redacao'} className={styles.card}>
                    <span>10/03/2026</span>
                    <h2>Tema da redação</h2>
                    <h1>880</h1>
                </button>
            </div>
        </div>
    );
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
    const session = await getSession({ req });

    if (!session?.user) {
        return {
            redirect: {
                destination: '/login',
                permanent: false,
            }
        }
    }


    return {
        props: {
            user: {
                email: session?.user?.email,
            }
        },
    };
};