import Head from "next/head";

import styles from "./styles.module.css";
import { CircularProgressbar, buildStyles } from 'react-circular-progressbar';
import 'react-circular-progressbar/dist/styles.css';
import { FaArrowLeft, FaArrowRight } from "react-icons/fa";
import { useEffect, useState } from "react";

import { GetServerSideProps } from "next";
import { getSession, useSession } from "next-auth/react";

import { db } from "@/services/firebaseConnection";
import { addDoc, collection, query, orderBy, where, onSnapshot } from "firebase/firestore";

interface HomeProps {
    user: {
        email: string
    }
}

interface RedacaoProps {
    id: string;
    created: Date;
    tema: string;
    c1: number;
    c2: number;
    c3: number;
    c4: number;
    c5: number;
    total: number;
    user: string;

}

export default function Historico({ user }: HomeProps) {

    useEffect(() => {
        async function loadRedacoes() {
            const redacoesRef = collection(db, "Redações");
            const q = query(
                redacoesRef,
                where("user", "==", user?.email),
                orderBy("created", "desc")
            )

            onSnapshot(q, (snapshot) => {
                let lista = [] as RedacaoProps[];
                snapshot.forEach((doc) => {
                    lista.push({
                        id: doc.id,
                        created: doc.data().created?.toDate(),
                        tema: doc.data().tema,
                        c1: doc.data().c1,
                        c2: doc.data().c2,
                        c3: doc.data().c3,
                        c4: doc.data().c4,
                        c5: doc.data().c5,
                        total: doc.data().total,
                        user: doc.data().user
                    })

                    setRedacoes(lista);
                })
            })
        }

        loadRedacoes();
    }, [user?.email])

    const [redacoes, setRedacoes] = useState<RedacaoProps[]>([])

    return (
        <div className={styles.container}>

            <Head>
                <title>Historico - Corrige-Me</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.info}>
                <h1 className={styles.title}>Minhas Redações</h1>
                {redacoes.map((item) => (
                    <button key={item.id} onClick={() => location.href = `/historico/redacao?id=${item.id}`} className={styles.card}>
                        <span>{item.created?.toLocaleDateString()}</span>
                        <h2>{item.tema}</h2>
                        <h1>{item.total}</h1>
                    </button>
                ))}
            </div>
        </div>
    );
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
    const session = await getSession({ req });

    if (!session?.user) {
        return {
            redirect: {
                destination: '/login',
                permanent: false,
            }
        }
    }


    return {
        props: {
            user: {
                email: session?.user?.email,
            }
        },
    };
};