import Head from "next/head";

import styles from "@/styles/Home.module.css";
import { CircularProgressbar, buildStyles } from 'react-circular-progressbar';
import 'react-circular-progressbar/dist/styles.css';
import { useEffect } from "react";

import { GetServerSideProps } from "next";
import { getSession, useSession } from "next-auth/react";


export default function Home() {
    const { data: session, status } = useSession();
    useEffect(() => {
        if (typeof window !== "undefined") {
            const temaSalvo = localStorage.getItem("Tema");
            if (temaSalvo) {
              localStorage.removeItem("Tema")
            }
        }

        console.log()
    }, []);

  return (
    <div className={styles.container}>
  
      <Head>
        <title>Painel - Corrige-Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.info}>
        <h1 className={styles.title}>Olá, {session?.user?.name as string}</h1>
        <div className={styles.card}>
          <h2 className={styles.cardTitle}>Redações Corrigidas</h2>
          <h1 className={styles.cardNumber}>0</h1>
        </div>
        <div className={styles.card}>
          <h2 className={styles.cardTitle}>Correções Restantes</h2>
          <h1 className={styles.cardNumber}>0</h1>
        </div>
        <div className={styles.cardProgress}>
          <h2 className={styles.cardTitle}>Maior Nota</h2>
          <CircularProgressbar className={styles.progressBar} styles={buildStyles({
            rotation: 0.75,
            textColor: '#34498B',
            pathColor: '#34498B',
            textSize: '18px',
            strokeLinecap: "butt"
          })} value={880} maxValue={1000} text="880" circleRatio={0.5} />
        </div>
      </div>

      <div className={styles.actions}>
        <button onClick={() => {location.href = '/corrigir'}} className={styles.button}>
          <span className={styles.buttonTop}>Escrever nova redação</span>
          <span className={styles.buttonBottom}>Pratique para o ENEM com temas reais</span>
        </button>
        <button onClick={() => {location.href = '/historico'}} className={styles.buttonSecondary}>
          <span className={styles.buttonTop}>Ver minhas redações</span>
          <span className={styles.buttonBottom}>Reveja correções e notas</span>
        </button>
      </div>

    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
    const session = await getSession({ req });

    if (!session?.user) {
        return {
            redirect: {
                destination: '/login',
                permanent: false,
            }
        }
    }


    return {
        props: {
            user: {
                email: session?.user?.email,
            }
        },
    };
};