
import { FaArrowRight, FaArrowLeft } from 'react-icons/fa'
import styles from './styles.module.css'
import { FormEvent, useEffect } from 'react'
import api from '@/services/api'

import Head from "next/head"
import { useState } from 'react'

import { GetServerSideProps } from "next";
import { getSession, useSession } from "next-auth/react";

import { db } from "@/services/firebaseConnection";
import { addDoc, collection } from "firebase/firestore";

interface HomeProps {
    user: {
        email: string
    }
}

export default function Texto({ user }: HomeProps) {

    const [tema, setTema] = useState('');
    const [erro, setErro] = useState('');
    const [loading, setLoading] = useState(false);
    const [redacao, setRedacao] = useState('');

    useEffect(() => {
        if (typeof window !== "undefined") {
            const temaSalvo = localStorage.getItem("Tema");
            if (temaSalvo) {
                setTema(temaSalvo);
            } else {
                location.href = '/'
            }
        }
    }, []);

    const changeRedacao = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
        setRedacao(e.target.value);
        console.log(redacao);
    }

    const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {


        setLoading(true);
        setErro("");
        e.preventDefault();

        try {
            const response = await api.post("/corrigir", {
                tema: tema,
                texto: redacao
            });


            const data = response.data;

            await addDoc(collection(db, "Redações"), {
                tema: tema,
                c1: data.competencias.c1,
                c2: data.competencias.c2,
                c3: data.competencias.c3,
                c4: data.competencias.c4,
                c5: data.competencias.c5,
                total: data.nota_total,
                user: user?.email,
                created: new Date()
            })

        } catch (err) {
            console.error(err);
            setErro("Não foi possível corrigir a redação. Tente novamente mais tarde.");
        } finally {
            setLoading(false);

        }
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Nova Redação - Corrige-Me</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <form onSubmit={handleSubmit} className={styles.content}>
                <button onClick={() => location.href = '/corrigir'} className={styles.backButton}><FaArrowLeft size={24} /></button>
                <h1 className={styles.title}>{tema}</h1>
                <textarea value={redacao} onChange={changeRedacao} placeholder='Escreva aqui a sua redação' required className={styles.input}></textarea>
                <div className={styles.buttonDiv}>
                    <button className={styles.nextButton}>Corrigir <FaArrowRight size={24} /> </button>
                </div>
            </form>
        </div>
    )

}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
    const session = await getSession({ req });

    if (!session?.user) {
        return {
            redirect: {
                destination: '/login',
                permanent: false,
            }
        }
    }


    return {
        props: {
            user: {
                email: session?.user?.email,
            }
        },
    };
};