
import { FaArrowRight, FaArrowLeft } from 'react-icons/fa'
import styles from './styles.module.css'
import { FormEvent, useEffect } from 'react'

import Head from "next/head"
import { useState } from 'react'

export default function Texto() {

    const [tema, setTema] = useState('');

    useEffect(() => {
        if (typeof window !== "undefined") {
            const temaSalvo = localStorage.getItem("Tema");
            if (temaSalvo) {
                setTema(temaSalvo);
            }else{
                location.href = '/'
            }
        }
    }, []);


    const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
        localStorage.removeItem('Tema')
        e.preventDefault();
        location.href = '/historico/redacao'
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Nova Redação - Corrige-Me</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <form onSubmit={handleSubmit} className={styles.content}>
                <button onClick={() => location.href = '/corrigir'} className={styles.backButton}><FaArrowLeft size={24}/></button>
                <h1 className={styles.title}>{tema}</h1>
                <textarea placeholder='Escreva aqui a sua redação' required className={styles.input}></textarea>
                <div className={styles.buttonDiv}>
                    <button className={styles.nextButton}>Corrigir <FaArrowRight size={24} /> </button>
                </div>
            </form>
        </div>
    )
}