
import { FaArrowRight } from 'react-icons/fa'
import styles from './styles.module.css'
import { FormEvent } from 'react'

import Head from "next/head"
import { useState, useEffect } from 'react'

import { GetServerSideProps } from "next";
import { getSession, useSession } from "next-auth/react";

export default function Corrigir() {

    const [tema, setTema] = useState('');


    const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
        localStorage.setItem("Tema", tema);
        e.preventDefault();
        location.href = '/corrigir/texto';
    }

    useEffect(() => {
        if (typeof window !== "undefined") {
            const temaSalvo = localStorage.getItem("Tema");
            if (temaSalvo) {
                setTema(temaSalvo);
            }
        }
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Nova Redação - Corrige-Me</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <form onSubmit={handleSubmit} className={styles.content}>
                <h1 className={styles.title}>Escolha o tema</h1>
                <input placeholder='Escreva aqui o tema da sua redação' value={tema} onChange={(e) => setTema(e.target.value)} className={styles.input} type="text" required />
                <div className={styles.buttonDiv}>
                    <button className={styles.nextButton}>Proximo <FaArrowRight size={24} /> </button>
                </div>
            </form>
        </div>
    )
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
    const session = await getSession({ req });

    if (!session?.user) {
        return {
            redirect: {
                destination: '/login',
                permanent: false,
            }
        }
    }


    return {
        props: {
            user: {
                email: session?.user?.email,
            }
        },
    };
};