import Link from "next/link"
import styles from './styles.module.css'
import Head from "next/head"

export default function NotFound() {
    return (
        <div className={styles.container}>
            <Head>
                <title>404 - Não encontrado</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.info}>
                <h1>404 - Pagina não encontrada</h1>
                <p>Desculpa, nada pra ver aqui</p>
                <Link className={styles.link} href='/'>
                    Voltar pro inicio
                </Link>

            </div>
        </div>
    )
}