import Link from "next/link"
import styles from './styles.module.css'
import Head from "next/head"

import { GetServerSideProps } from "next";
import { getSession, useSession } from "next-auth/react";

export default function NotFound() {
    return (
        <div className={styles.container}>
            <Head>
                <title>404 - Não encontrado</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.info}>
                <h1>404 - Pagina não encontrada</h1>
                <p>Desculpa, nada pra ver aqui</p>
                <Link className={styles.link} href='/'>
                    Voltar pro inicio
                </Link>

            </div>
        </div>
    )
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
    const session = await getSession({ req });

    if (!session?.user) {
        return {
            redirect: {
                destination: '/login',
                permanent: false,
            }
        }
    }


    return {
        props: {
            user: {
                email: session?.user?.email,
            }
        },
    };
};